### ISSUE TITLE
Request to add Openspeedtest

### ISSUE THREAD

**Issue by YoshiKill** [muink/luci-app-netspeedtest#11]
Hello, thank you for great speed package. I have one request. There is one nice project for speed Analise [OpenSpeedTest™](https://openspeedtest.com/?Run&ref=Github) can you add it in to this packet of utility? It will be greet.

**Comment by muink** [comment]
Looks good and does not require the introduction of additional binaries.

**Comment by muink** [comment]
Pls try 4fd196a7879e5338aea384f9d69f251dd6d17807

**Comment by YoshiKill** [comment]
> Pls try [4fd196a](https://github.com/muink/luci-app-netspeedtest/commit/4fd196a7879e5338aea384f9d69f251dd6d17807)

yep that work fine, thanks! Maybe you can add server function to? To test internal lan speed with Ost from other device just from browser.

**Comment by BenJamesAndo** [comment]
I'd also love to run OpenSpeedTest server directly in OpenWRT, similar to librespeed Server with the Config tab. I like OpenSpeedTest because it shows the current downloading/uploading speed in a gauge chart, whereas librespeed only shows the numbers going up and down. Although some versions of librespeed has gauge charts, so not sure why this one doesn't.
